### ISSUE TITLE
desiredProximity not found error in 0.0.3 pod

### ISSUE THREAD

**Issue by pj4533** [ohayon/OWUProximityManager#1]
Pods/OWUProximityManager/Classes/OWUProximityManager.m:39:31: Property 'desiredProximity' not found on object of type 'OWUClientManager *'

**Comment by ohayon** [comment]
thanks for the heads up. just pushed a fix to cocoapods.
![](http://s3.amazonaws.com/rapgenius/1291131680_two-thumbs-up.jpg)
