### ISSUE TITLE
Enabling Server option is crashing application

### ISSUE THREAD

**Issue by rajatmohanty** [ohayon/OWUProximityManager#2]
i am currently using an iPad with iOS 7.0.4 and install this application. But when i am enabling the Server Slider , application is getting crashed.

**Comment by yunas** [comment]
@rajatmohanty this is because the "OWUProximityManagerConstants" file needs to be updated.
@ohwutup Can you brief how to generate the UUIDs and how to fill this constant file ?

**Comment by ohayon** [comment]
yeah for sure. if you just type in `uuidgen` into a terminal, it will spit out a fresh UUID. i can update this some more later on to avoid this problem. realized its not the best way to hold onto constants.

**Comment by ghost** [comment]
would you mind to provide a working example. Also, how many different UUIDS must be generated to make this work? I tried the same one and multiple different ones but client and server never find one another!?
